//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.HJ_ServiceSoap")]
    public interface HJ_ServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 TwRoomsResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TwRooms", ReplyAction="*")]
        Test.ServiceReference2.TwRoomsResponse TwRooms(Test.ServiceReference2.TwRoomsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TwRooms", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.ServiceReference2.TwRoomsResponse> TwRoomsAsync(Test.ServiceReference2.TwRoomsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWordResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWord", ReplyAction="*")]
        Test.ServiceReference2.HelloWordResponse HelloWord(Test.ServiceReference2.HelloWordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWord", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.ServiceReference2.HelloWordResponse> HelloWordAsync(Test.ServiceReference2.HelloWordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TwRoomsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TwRooms", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference2.TwRoomsRequestBody Body;
        
        public TwRoomsRequest() {
        }
        
        public TwRoomsRequest(Test.ServiceReference2.TwRoomsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TwRoomsRequestBody {
        
        public TwRoomsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TwRoomsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TwRoomsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference2.TwRoomsResponseBody Body;
        
        public TwRoomsResponse() {
        }
        
        public TwRoomsResponse(Test.ServiceReference2.TwRoomsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TwRoomsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TwRoomsResult;
        
        public TwRoomsResponseBody() {
        }
        
        public TwRoomsResponseBody(string TwRoomsResult) {
            this.TwRoomsResult = TwRoomsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWord", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference2.HelloWordRequestBody Body;
        
        public HelloWordRequest() {
        }
        
        public HelloWordRequest(Test.ServiceReference2.HelloWordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWordRequestBody {
        
        public HelloWordRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWordResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference2.HelloWordResponseBody Body;
        
        public HelloWordResponse() {
        }
        
        public HelloWordResponse(Test.ServiceReference2.HelloWordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWordResult;
        
        public HelloWordResponseBody() {
        }
        
        public HelloWordResponseBody(string HelloWordResult) {
            this.HelloWordResult = HelloWordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HJ_ServiceSoapChannel : Test.ServiceReference2.HJ_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HJ_ServiceSoapClient : System.ServiceModel.ClientBase<Test.ServiceReference2.HJ_ServiceSoap>, Test.ServiceReference2.HJ_ServiceSoap {
        
        public HJ_ServiceSoapClient() {
        }
        
        public HJ_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HJ_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HJ_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HJ_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.ServiceReference2.TwRoomsResponse Test.ServiceReference2.HJ_ServiceSoap.TwRooms(Test.ServiceReference2.TwRoomsRequest request) {
            return base.Channel.TwRooms(request);
        }
        
        public string TwRooms() {
            Test.ServiceReference2.TwRoomsRequest inValue = new Test.ServiceReference2.TwRoomsRequest();
            inValue.Body = new Test.ServiceReference2.TwRoomsRequestBody();
            Test.ServiceReference2.TwRoomsResponse retVal = ((Test.ServiceReference2.HJ_ServiceSoap)(this)).TwRooms(inValue);
            return retVal.Body.TwRoomsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.ServiceReference2.TwRoomsResponse> Test.ServiceReference2.HJ_ServiceSoap.TwRoomsAsync(Test.ServiceReference2.TwRoomsRequest request) {
            return base.Channel.TwRoomsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference2.TwRoomsResponse> TwRoomsAsync() {
            Test.ServiceReference2.TwRoomsRequest inValue = new Test.ServiceReference2.TwRoomsRequest();
            inValue.Body = new Test.ServiceReference2.TwRoomsRequestBody();
            return ((Test.ServiceReference2.HJ_ServiceSoap)(this)).TwRoomsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.ServiceReference2.HelloWordResponse Test.ServiceReference2.HJ_ServiceSoap.HelloWord(Test.ServiceReference2.HelloWordRequest request) {
            return base.Channel.HelloWord(request);
        }
        
        public string HelloWord() {
            Test.ServiceReference2.HelloWordRequest inValue = new Test.ServiceReference2.HelloWordRequest();
            inValue.Body = new Test.ServiceReference2.HelloWordRequestBody();
            Test.ServiceReference2.HelloWordResponse retVal = ((Test.ServiceReference2.HJ_ServiceSoap)(this)).HelloWord(inValue);
            return retVal.Body.HelloWordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.ServiceReference2.HelloWordResponse> Test.ServiceReference2.HJ_ServiceSoap.HelloWordAsync(Test.ServiceReference2.HelloWordRequest request) {
            return base.Channel.HelloWordAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference2.HelloWordResponse> HelloWordAsync() {
            Test.ServiceReference2.HelloWordRequest inValue = new Test.ServiceReference2.HelloWordRequest();
            inValue.Body = new Test.ServiceReference2.HelloWordRequestBody();
            return ((Test.ServiceReference2.HJ_ServiceSoap)(this)).HelloWordAsync(inValue);
        }
    }
}
