//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Test.HMCRM {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HJ_ServiceSoap", Namespace="http://tempuri.org/")]
    public partial class HJ_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TwBuildingServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback TwRoomServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback TwCustomerServiceOperationCompleted;
        
        private System.Threading.SendOrPostCallback TwCustomerMemberServiceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HJ_Service() {
            this.Url = global::Test.Properties.Settings.Default.Test_HMCRM_HJ_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TwBuildingServiceCompletedEventHandler TwBuildingServiceCompleted;
        
        /// <remarks/>
        public event TwRoomServiceCompletedEventHandler TwRoomServiceCompleted;
        
        /// <remarks/>
        public event TwCustomerServiceCompletedEventHandler TwCustomerServiceCompleted;
        
        /// <remarks/>
        public event TwCustomerMemberServiceCompletedEventHandler TwCustomerMemberServiceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TwBuildingService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TwBuildingService(string strCommName, BuildEntity[] ModelList) {
            object[] results = this.Invoke("TwBuildingService", new object[] {
                        strCommName,
                        ModelList});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TwBuildingServiceAsync(string strCommName, BuildEntity[] ModelList) {
            this.TwBuildingServiceAsync(strCommName, ModelList, null);
        }
        
        /// <remarks/>
        public void TwBuildingServiceAsync(string strCommName, BuildEntity[] ModelList, object userState) {
            if ((this.TwBuildingServiceOperationCompleted == null)) {
                this.TwBuildingServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTwBuildingServiceOperationCompleted);
            }
            this.InvokeAsync("TwBuildingService", new object[] {
                        strCommName,
                        ModelList}, this.TwBuildingServiceOperationCompleted, userState);
        }
        
        private void OnTwBuildingServiceOperationCompleted(object arg) {
            if ((this.TwBuildingServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TwBuildingServiceCompleted(this, new TwBuildingServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TwRoomService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TwRoomService(string strCommName, HouseEntity[] ModelList) {
            object[] results = this.Invoke("TwRoomService", new object[] {
                        strCommName,
                        ModelList});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TwRoomServiceAsync(string strCommName, HouseEntity[] ModelList) {
            this.TwRoomServiceAsync(strCommName, ModelList, null);
        }
        
        /// <remarks/>
        public void TwRoomServiceAsync(string strCommName, HouseEntity[] ModelList, object userState) {
            if ((this.TwRoomServiceOperationCompleted == null)) {
                this.TwRoomServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTwRoomServiceOperationCompleted);
            }
            this.InvokeAsync("TwRoomService", new object[] {
                        strCommName,
                        ModelList}, this.TwRoomServiceOperationCompleted, userState);
        }
        
        private void OnTwRoomServiceOperationCompleted(object arg) {
            if ((this.TwRoomServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TwRoomServiceCompleted(this, new TwRoomServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TwCustomerService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TwCustomerService(string strCommName, CustomerEntity[] ModelList) {
            object[] results = this.Invoke("TwCustomerService", new object[] {
                        strCommName,
                        ModelList});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TwCustomerServiceAsync(string strCommName, CustomerEntity[] ModelList) {
            this.TwCustomerServiceAsync(strCommName, ModelList, null);
        }
        
        /// <remarks/>
        public void TwCustomerServiceAsync(string strCommName, CustomerEntity[] ModelList, object userState) {
            if ((this.TwCustomerServiceOperationCompleted == null)) {
                this.TwCustomerServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTwCustomerServiceOperationCompleted);
            }
            this.InvokeAsync("TwCustomerService", new object[] {
                        strCommName,
                        ModelList}, this.TwCustomerServiceOperationCompleted, userState);
        }
        
        private void OnTwCustomerServiceOperationCompleted(object arg) {
            if ((this.TwCustomerServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TwCustomerServiceCompleted(this, new TwCustomerServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TwCustomerMemberService", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TwCustomerMemberService(string strCommName, CustomerMemberEntity[] ModelList) {
            object[] results = this.Invoke("TwCustomerMemberService", new object[] {
                        strCommName,
                        ModelList});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TwCustomerMemberServiceAsync(string strCommName, CustomerMemberEntity[] ModelList) {
            this.TwCustomerMemberServiceAsync(strCommName, ModelList, null);
        }
        
        /// <remarks/>
        public void TwCustomerMemberServiceAsync(string strCommName, CustomerMemberEntity[] ModelList, object userState) {
            if ((this.TwCustomerMemberServiceOperationCompleted == null)) {
                this.TwCustomerMemberServiceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTwCustomerMemberServiceOperationCompleted);
            }
            this.InvokeAsync("TwCustomerMemberService", new object[] {
                        strCommName,
                        ModelList}, this.TwCustomerMemberServiceOperationCompleted, userState);
        }
        
        private void OnTwCustomerMemberServiceOperationCompleted(object arg) {
            if ((this.TwCustomerMemberServiceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TwCustomerMemberServiceCompleted(this, new TwCustomerMemberServiceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BuildEntity {
        
        private string numberField;
        
        private string otherName1Field;
        
        private string communityNameField;
        
        private string otherName2Field;
        
        private string communityNumberField;
        
        private string nameField;
        
        private string saleNameField;
        
        private string streetField;
        
        private string addressField;
        
        private System.DateTime startBuildDateField;
        
        private System.DateTime joinDateField;
        
        private decimal planBuildAreaField;
        
        private decimal buildAreaField;
        
        private decimal overBuildAreaField;
        
        private decimal underBuildAreaField;
        
        private decimal houseNumField;
        
        private decimal planUseAreaField;
        
        private decimal useAreaField;
        
        private string purposeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OtherName1 {
            get {
                return this.otherName1Field;
            }
            set {
                this.otherName1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CommunityName {
            get {
                return this.communityNameField;
            }
            set {
                this.communityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OtherName2 {
            get {
                return this.otherName2Field;
            }
            set {
                this.otherName2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CommunityNumber {
            get {
                return this.communityNumberField;
            }
            set {
                this.communityNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SaleName {
            get {
                return this.saleNameField;
            }
            set {
                this.saleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime StartBuildDate {
            get {
                return this.startBuildDateField;
            }
            set {
                this.startBuildDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime JoinDate {
            get {
                return this.joinDateField;
            }
            set {
                this.joinDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PlanBuildArea {
            get {
                return this.planBuildAreaField;
            }
            set {
                this.planBuildAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal BuildArea {
            get {
                return this.buildAreaField;
            }
            set {
                this.buildAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal OverBuildArea {
            get {
                return this.overBuildAreaField;
            }
            set {
                this.overBuildAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal UnderBuildArea {
            get {
                return this.underBuildAreaField;
            }
            set {
                this.underBuildAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal HouseNum {
            get {
                return this.houseNumField;
            }
            set {
                this.houseNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PlanUseArea {
            get {
                return this.planUseAreaField;
            }
            set {
                this.planUseAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal UseArea {
            get {
                return this.useAreaField;
            }
            set {
                this.useAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Purpose {
            get {
                return this.purposeField;
            }
            set {
                this.purposeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerMemberEntity {
        
        private string customerRelationField;
        
        private string customerNumberField;
        
        private string organizationNumberField;
        
        private string nameField;
        
        private string customerTypeField;
        
        private string certificateTypeField;
        
        private string personIDField;
        
        private string addressField;
        
        private string mobileField;
        
        private string phoneField;
        
        private string phone2Field;
        
        private string sexField;
        
        private string corporationField;
        
        private string licenseNumField;
        
        private string isOwnerField;
        
        /// <remarks/>
        public string CustomerRelation {
            get {
                return this.customerRelationField;
            }
            set {
                this.customerRelationField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationNumber {
            get {
                return this.organizationNumberField;
            }
            set {
                this.organizationNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerType {
            get {
                return this.customerTypeField;
            }
            set {
                this.customerTypeField = value;
            }
        }
        
        /// <remarks/>
        public string CertificateType {
            get {
                return this.certificateTypeField;
            }
            set {
                this.certificateTypeField = value;
            }
        }
        
        /// <remarks/>
        public string PersonID {
            get {
                return this.personIDField;
            }
            set {
                this.personIDField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
            }
        }
        
        /// <remarks/>
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        public string Corporation {
            get {
                return this.corporationField;
            }
            set {
                this.corporationField = value;
            }
        }
        
        /// <remarks/>
        public string LicenseNum {
            get {
                return this.licenseNumField;
            }
            set {
                this.licenseNumField = value;
            }
        }
        
        /// <remarks/>
        public string IsOwner {
            get {
                return this.isOwnerField;
            }
            set {
                this.isOwnerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerHouseEntity {
        
        private string houseNumberField;
        
        private string buildNumberField;
        
        private System.DateTime inDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HouseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                this.houseNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BuildNumber {
            get {
                return this.buildNumberField;
            }
            set {
                this.buildNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime InDate {
            get {
                return this.inDateField;
            }
            set {
                this.inDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerEntity {
        
        private CustomerHouseEntity[] customerHousesField;
        
        private string customerNumberField;
        
        private string organizationNumberField;
        
        private string nameField;
        
        private string customerTypeField;
        
        private string certificateTypeField;
        
        private string personIDField;
        
        private string addressField;
        
        private string mobileField;
        
        private string phoneField;
        
        private string phone2Field;
        
        private string emailField;
        
        private string workPlaceField;
        
        private string sexField;
        
        private string marryStateField;
        
        private string customerCountryField;
        
        private string degreeField;
        
        private string customerOccpField;
        
        private string corporationField;
        
        private string compTypeField;
        
        private string licenseNumField;
        
        private bool isOwnerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CustomerHouses")]
        public CustomerHouseEntity[] CustomerHouses {
            get {
                return this.customerHousesField;
            }
            set {
                this.customerHousesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CustomerNumber {
            get {
                return this.customerNumberField;
            }
            set {
                this.customerNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OrganizationNumber {
            get {
                return this.organizationNumberField;
            }
            set {
                this.organizationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CustomerType {
            get {
                return this.customerTypeField;
            }
            set {
                this.customerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CertificateType {
            get {
                return this.certificateTypeField;
            }
            set {
                this.certificateTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PersonID {
            get {
                return this.personIDField;
            }
            set {
                this.personIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string WorkPlace {
            get {
                return this.workPlaceField;
            }
            set {
                this.workPlaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sex {
            get {
                return this.sexField;
            }
            set {
                this.sexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MarryState {
            get {
                return this.marryStateField;
            }
            set {
                this.marryStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CustomerCountry {
            get {
                return this.customerCountryField;
            }
            set {
                this.customerCountryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Degree {
            get {
                return this.degreeField;
            }
            set {
                this.degreeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CustomerOccp {
            get {
                return this.customerOccpField;
            }
            set {
                this.customerOccpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Corporation {
            get {
                return this.corporationField;
            }
            set {
                this.corporationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CompType {
            get {
                return this.compTypeField;
            }
            set {
                this.compTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LicenseNum {
            get {
                return this.licenseNumField;
            }
            set {
                this.licenseNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsOwner {
            get {
                return this.isOwnerField;
            }
            set {
                this.isOwnerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class HouseEntity {
        
        private string houseNameField;
        
        private string simpleHouseNumField;
        
        private string buildNumberField;
        
        private string houseNumerField;
        
        private string numberField;
        
        private string houseTakeStatusField;
        
        private System.DateTime openingDateField;
        
        private System.DateTime factDateField;
        
        private System.DateTime actualDateField;
        
        private decimal buildAreaField;
        
        private decimal actualBuiltupAreaField;
        
        private decimal forecastBuiltupAreaField;
        
        private decimal forecastSetAreaField;
        
        private decimal actualSetAreaField;
        
        private decimal gardenAreaField;
        
        private string houseShapeField;
        
        private string directionField;
        
        private string addressField;
        
        private string purposeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HouseName {
            get {
                return this.houseNameField;
            }
            set {
                this.houseNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SimpleHouseNum {
            get {
                return this.simpleHouseNumField;
            }
            set {
                this.simpleHouseNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BuildNumber {
            get {
                return this.buildNumberField;
            }
            set {
                this.buildNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HouseNumer {
            get {
                return this.houseNumerField;
            }
            set {
                this.houseNumerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HouseTakeStatus {
            get {
                return this.houseTakeStatusField;
            }
            set {
                this.houseTakeStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime OpeningDate {
            get {
                return this.openingDateField;
            }
            set {
                this.openingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime FactDate {
            get {
                return this.factDateField;
            }
            set {
                this.factDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ActualDate {
            get {
                return this.actualDateField;
            }
            set {
                this.actualDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal BuildArea {
            get {
                return this.buildAreaField;
            }
            set {
                this.buildAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ActualBuiltupArea {
            get {
                return this.actualBuiltupAreaField;
            }
            set {
                this.actualBuiltupAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ForecastBuiltupArea {
            get {
                return this.forecastBuiltupAreaField;
            }
            set {
                this.forecastBuiltupAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ForecastSetArea {
            get {
                return this.forecastSetAreaField;
            }
            set {
                this.forecastSetAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal ActualSetArea {
            get {
                return this.actualSetAreaField;
            }
            set {
                this.actualSetAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal GardenArea {
            get {
                return this.gardenAreaField;
            }
            set {
                this.gardenAreaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HouseShape {
            get {
                return this.houseShapeField;
            }
            set {
                this.houseShapeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Purpose {
            get {
                return this.purposeField;
            }
            set {
                this.purposeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TwBuildingServiceCompletedEventHandler(object sender, TwBuildingServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TwBuildingServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TwBuildingServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TwRoomServiceCompletedEventHandler(object sender, TwRoomServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TwRoomServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TwRoomServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TwCustomerServiceCompletedEventHandler(object sender, TwCustomerServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TwCustomerServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TwCustomerServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TwCustomerMemberServiceCompletedEventHandler(object sender, TwCustomerMemberServiceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TwCustomerMemberServiceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TwCustomerMemberServiceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591