//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.MasterExtendService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.extend.master.kmss.landray.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.extend.master.kmss.landray.com/", ConfigurationName="MasterExtendService.IMasterExtendWebserviceService")]
    public interface IMasterExtendWebserviceService {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Test.MasterExtendService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Test.MasterExtendService.getInfoByIndentifyResponse getInfoByIndentify(Test.MasterExtendService.getInfoByIndentify request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.MasterExtendService.getInfoByIndentifyResponse> getInfoByIndentifyAsync(Test.MasterExtendService.getInfoByIndentify request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfoByIndentify", WrapperNamespace="http://webservice.extend.master.kmss.landray.com/", IsWrapped=true)]
    public partial class getInfoByIndentify {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.extend.master.kmss.landray.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paramJson;
        
        public getInfoByIndentify() {
        }
        
        public getInfoByIndentify(string paramJson) {
            this.paramJson = paramJson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getInfoByIndentifyResponse", WrapperNamespace="http://webservice.extend.master.kmss.landray.com/", IsWrapped=true)]
    public partial class getInfoByIndentifyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.extend.master.kmss.landray.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getInfoByIndentifyResponse() {
        }
        
        public getInfoByIndentifyResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMasterExtendWebserviceServiceChannel : Test.MasterExtendService.IMasterExtendWebserviceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MasterExtendWebserviceServiceClient : System.ServiceModel.ClientBase<Test.MasterExtendService.IMasterExtendWebserviceService>, Test.MasterExtendService.IMasterExtendWebserviceService {
        
        public MasterExtendWebserviceServiceClient() {
        }
        
        public MasterExtendWebserviceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MasterExtendWebserviceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterExtendWebserviceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterExtendWebserviceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.MasterExtendService.getInfoByIndentifyResponse Test.MasterExtendService.IMasterExtendWebserviceService.getInfoByIndentify(Test.MasterExtendService.getInfoByIndentify request) {
            return base.Channel.getInfoByIndentify(request);
        }
        
        public string getInfoByIndentify(string paramJson) {
            Test.MasterExtendService.getInfoByIndentify inValue = new Test.MasterExtendService.getInfoByIndentify();
            inValue.paramJson = paramJson;
            Test.MasterExtendService.getInfoByIndentifyResponse retVal = ((Test.MasterExtendService.IMasterExtendWebserviceService)(this)).getInfoByIndentify(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.MasterExtendService.getInfoByIndentifyResponse> Test.MasterExtendService.IMasterExtendWebserviceService.getInfoByIndentifyAsync(Test.MasterExtendService.getInfoByIndentify request) {
            return base.Channel.getInfoByIndentifyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.MasterExtendService.getInfoByIndentifyResponse> getInfoByIndentifyAsync(string paramJson) {
            Test.MasterExtendService.getInfoByIndentify inValue = new Test.MasterExtendService.getInfoByIndentify();
            inValue.paramJson = paramJson;
            return ((Test.MasterExtendService.IMasterExtendWebserviceService)(this)).getInfoByIndentifyAsync(inValue);
        }
    }
}
