//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.ServiceReference3 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.HJ_ServiceSoap")]
    public interface HJ_ServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 CommID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TwRooms", ReplyAction="*")]
        Test.ServiceReference3.TwRoomsResponse TwRooms(Test.ServiceReference3.TwRoomsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TwRooms", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.ServiceReference3.TwRoomsResponse> TwRoomsAsync(Test.ServiceReference3.TwRoomsRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 ADDResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ADD", ReplyAction="*")]
        Test.ServiceReference3.ADDResponse ADD(Test.ServiceReference3.ADDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ADD", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.ServiceReference3.ADDResponse> ADDAsync(Test.ServiceReference3.ADDRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 lists 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IList", ReplyAction="*")]
        Test.ServiceReference3.IListResponse IList(Test.ServiceReference3.IListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IList", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.ServiceReference3.IListResponse> IListAsync(Test.ServiceReference3.IListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TwRoomsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TwRooms", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference3.TwRoomsRequestBody Body;
        
        public TwRoomsRequest() {
        }
        
        public TwRoomsRequest(Test.ServiceReference3.TwRoomsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TwRoomsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CorpID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CommID;
        
        public TwRoomsRequestBody() {
        }
        
        public TwRoomsRequestBody(int CorpID, string CommID) {
            this.CorpID = CorpID;
            this.CommID = CommID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TwRoomsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TwRoomsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference3.TwRoomsResponseBody Body;
        
        public TwRoomsResponse() {
        }
        
        public TwRoomsResponse(Test.ServiceReference3.TwRoomsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TwRoomsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TwRoomsResult;
        
        public TwRoomsResponseBody() {
        }
        
        public TwRoomsResponseBody(string TwRoomsResult) {
            this.TwRoomsResult = TwRoomsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ADDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ADD", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference3.ADDRequestBody Body;
        
        public ADDRequest() {
        }
        
        public ADDRequest(Test.ServiceReference3.ADDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ADDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int a;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int b;
        
        public ADDRequestBody() {
        }
        
        public ADDRequestBody(int a, int b) {
            this.a = a;
            this.b = b;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ADDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ADDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference3.ADDResponseBody Body;
        
        public ADDResponse() {
        }
        
        public ADDResponse(Test.ServiceReference3.ADDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ADDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ADDResult;
        
        public ADDResponseBody() {
        }
        
        public ADDResponseBody(string ADDResult) {
            this.ADDResult = ADDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IList", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference3.IListRequestBody Body;
        
        public IListRequest() {
        }
        
        public IListRequest(Test.ServiceReference3.IListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Test.ServiceReference3.ArrayOfString lists;
        
        public IListRequestBody() {
        }
        
        public IListRequestBody(Test.ServiceReference3.ArrayOfString lists) {
            this.lists = lists;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.ServiceReference3.IListResponseBody Body;
        
        public IListResponse() {
        }
        
        public IListResponse(Test.ServiceReference3.IListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IListResult;
        
        public IListResponseBody() {
        }
        
        public IListResponseBody(string IListResult) {
            this.IListResult = IListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HJ_ServiceSoapChannel : Test.ServiceReference3.HJ_ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HJ_ServiceSoapClient : System.ServiceModel.ClientBase<Test.ServiceReference3.HJ_ServiceSoap>, Test.ServiceReference3.HJ_ServiceSoap {
        
        public HJ_ServiceSoapClient() {
        }
        
        public HJ_ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HJ_ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HJ_ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HJ_ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.ServiceReference3.TwRoomsResponse Test.ServiceReference3.HJ_ServiceSoap.TwRooms(Test.ServiceReference3.TwRoomsRequest request) {
            return base.Channel.TwRooms(request);
        }
        
        public string TwRooms(int CorpID, string CommID) {
            Test.ServiceReference3.TwRoomsRequest inValue = new Test.ServiceReference3.TwRoomsRequest();
            inValue.Body = new Test.ServiceReference3.TwRoomsRequestBody();
            inValue.Body.CorpID = CorpID;
            inValue.Body.CommID = CommID;
            Test.ServiceReference3.TwRoomsResponse retVal = ((Test.ServiceReference3.HJ_ServiceSoap)(this)).TwRooms(inValue);
            return retVal.Body.TwRoomsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.ServiceReference3.TwRoomsResponse> Test.ServiceReference3.HJ_ServiceSoap.TwRoomsAsync(Test.ServiceReference3.TwRoomsRequest request) {
            return base.Channel.TwRoomsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference3.TwRoomsResponse> TwRoomsAsync(int CorpID, string CommID) {
            Test.ServiceReference3.TwRoomsRequest inValue = new Test.ServiceReference3.TwRoomsRequest();
            inValue.Body = new Test.ServiceReference3.TwRoomsRequestBody();
            inValue.Body.CorpID = CorpID;
            inValue.Body.CommID = CommID;
            return ((Test.ServiceReference3.HJ_ServiceSoap)(this)).TwRoomsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.ServiceReference3.ADDResponse Test.ServiceReference3.HJ_ServiceSoap.ADD(Test.ServiceReference3.ADDRequest request) {
            return base.Channel.ADD(request);
        }
        
        public string ADD(int a, int b) {
            Test.ServiceReference3.ADDRequest inValue = new Test.ServiceReference3.ADDRequest();
            inValue.Body = new Test.ServiceReference3.ADDRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            Test.ServiceReference3.ADDResponse retVal = ((Test.ServiceReference3.HJ_ServiceSoap)(this)).ADD(inValue);
            return retVal.Body.ADDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.ServiceReference3.ADDResponse> Test.ServiceReference3.HJ_ServiceSoap.ADDAsync(Test.ServiceReference3.ADDRequest request) {
            return base.Channel.ADDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference3.ADDResponse> ADDAsync(int a, int b) {
            Test.ServiceReference3.ADDRequest inValue = new Test.ServiceReference3.ADDRequest();
            inValue.Body = new Test.ServiceReference3.ADDRequestBody();
            inValue.Body.a = a;
            inValue.Body.b = b;
            return ((Test.ServiceReference3.HJ_ServiceSoap)(this)).ADDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.ServiceReference3.IListResponse Test.ServiceReference3.HJ_ServiceSoap.IList(Test.ServiceReference3.IListRequest request) {
            return base.Channel.IList(request);
        }
        
        public string IList(Test.ServiceReference3.ArrayOfString lists) {
            Test.ServiceReference3.IListRequest inValue = new Test.ServiceReference3.IListRequest();
            inValue.Body = new Test.ServiceReference3.IListRequestBody();
            inValue.Body.lists = lists;
            Test.ServiceReference3.IListResponse retVal = ((Test.ServiceReference3.HJ_ServiceSoap)(this)).IList(inValue);
            return retVal.Body.IListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.ServiceReference3.IListResponse> Test.ServiceReference3.HJ_ServiceSoap.IListAsync(Test.ServiceReference3.IListRequest request) {
            return base.Channel.IListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.ServiceReference3.IListResponse> IListAsync(Test.ServiceReference3.ArrayOfString lists) {
            Test.ServiceReference3.IListRequest inValue = new Test.ServiceReference3.IListRequest();
            inValue.Body = new Test.ServiceReference3.IListRequestBody();
            inValue.Body.lists = lists;
            return ((Test.ServiceReference3.HJ_ServiceSoap)(this)).IListAsync(inValue);
        }
    }
}
