//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.KmReviewService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.review.km.kmss.landray.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.review.km.kmss.landray.com/")]
    public partial class attachmentForm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fdKeyField;
        
        private string fdFileNameField;
        
        private byte[] fdAttachmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fdKey {
            get {
                return this.fdKeyField;
            }
            set {
                this.fdKeyField = value;
                this.RaisePropertyChanged("fdKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fdFileName {
            get {
                return this.fdFileNameField;
            }
            set {
                this.fdFileNameField = value;
                this.RaisePropertyChanged("fdFileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] fdAttachment {
            get {
                return this.fdAttachmentField;
            }
            set {
                this.fdAttachmentField = value;
                this.RaisePropertyChanged("fdAttachment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.review.km.kmss.landray.com/")]
    public partial class kmReviewParamterForm : object, System.ComponentModel.INotifyPropertyChanged {
        
        private attachmentForm[] attachmentFormsField;
        
        private string docContentField;
        
        private string docCreatorField;
        
        private string docPropertyField;
        
        private string docStatusField;
        
        private string docSubjectField;
        
        private string fdKeywordField;
        
        private string fdTemplateIdField;
        
        private string flowParamField;
        
        private string formValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attachmentForms", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public attachmentForm[] attachmentForms {
            get {
                return this.attachmentFormsField;
            }
            set {
                this.attachmentFormsField = value;
                this.RaisePropertyChanged("attachmentForms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string docContent {
            get {
                return this.docContentField;
            }
            set {
                this.docContentField = value;
                this.RaisePropertyChanged("docContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string docCreator {
            get {
                return this.docCreatorField;
            }
            set {
                this.docCreatorField = value;
                this.RaisePropertyChanged("docCreator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string docProperty {
            get {
                return this.docPropertyField;
            }
            set {
                this.docPropertyField = value;
                this.RaisePropertyChanged("docProperty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string docStatus {
            get {
                return this.docStatusField;
            }
            set {
                this.docStatusField = value;
                this.RaisePropertyChanged("docStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string docSubject {
            get {
                return this.docSubjectField;
            }
            set {
                this.docSubjectField = value;
                this.RaisePropertyChanged("docSubject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string fdKeyword {
            get {
                return this.fdKeywordField;
            }
            set {
                this.fdKeywordField = value;
                this.RaisePropertyChanged("fdKeyword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string fdTemplateId {
            get {
                return this.fdTemplateIdField;
            }
            set {
                this.fdTemplateIdField = value;
                this.RaisePropertyChanged("fdTemplateId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string flowParam {
            get {
                return this.flowParamField;
            }
            set {
                this.flowParamField = value;
                this.RaisePropertyChanged("flowParam");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string formValues {
            get {
                return this.formValuesField;
            }
            set {
                this.formValuesField = value;
                this.RaisePropertyChanged("formValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.review.km.kmss.landray.com/", ConfigurationName="KmReviewService.IKmReviewWebserviceService")]
    public interface IKmReviewWebserviceService {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Test.KmReviewService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Test.KmReviewService.addReviewResponse addReview(Test.KmReviewService.addReview request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.KmReviewService.addReviewResponse> addReviewAsync(Test.KmReviewService.addReview request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addReview", WrapperNamespace="http://webservice.review.km.kmss.landray.com/", IsWrapped=true)]
    public partial class addReview {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.review.km.kmss.landray.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Test.KmReviewService.kmReviewParamterForm arg0;
        
        public addReview() {
        }
        
        public addReview(Test.KmReviewService.kmReviewParamterForm arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addReviewResponse", WrapperNamespace="http://webservice.review.km.kmss.landray.com/", IsWrapped=true)]
    public partial class addReviewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://webservice.review.km.kmss.landray.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public addReviewResponse() {
        }
        
        public addReviewResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKmReviewWebserviceServiceChannel : Test.KmReviewService.IKmReviewWebserviceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KmReviewWebserviceServiceClient : System.ServiceModel.ClientBase<Test.KmReviewService.IKmReviewWebserviceService>, Test.KmReviewService.IKmReviewWebserviceService {
        
        public KmReviewWebserviceServiceClient() {
        }
        
        public KmReviewWebserviceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KmReviewWebserviceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KmReviewWebserviceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KmReviewWebserviceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.KmReviewService.addReviewResponse Test.KmReviewService.IKmReviewWebserviceService.addReview(Test.KmReviewService.addReview request) {
            return base.Channel.addReview(request);
        }
        
        public string addReview(Test.KmReviewService.kmReviewParamterForm arg0) {
            Test.KmReviewService.addReview inValue = new Test.KmReviewService.addReview();
            inValue.arg0 = arg0;
            Test.KmReviewService.addReviewResponse retVal = ((Test.KmReviewService.IKmReviewWebserviceService)(this)).addReview(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.KmReviewService.addReviewResponse> Test.KmReviewService.IKmReviewWebserviceService.addReviewAsync(Test.KmReviewService.addReview request) {
            return base.Channel.addReviewAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.KmReviewService.addReviewResponse> addReviewAsync(Test.KmReviewService.kmReviewParamterForm arg0) {
            Test.KmReviewService.addReview inValue = new Test.KmReviewService.addReview();
            inValue.arg0 = arg0;
            return ((Test.KmReviewService.IKmReviewWebserviceService)(this)).addReviewAsync(inValue);
        }
    }
}
